"""
dtr4_categories.py

@author: EAweblog
"""

from itertools import chain

ethnic_group_hierarchy = {
    "Total people - ethnic group": {
        "European": [
            "European nfd",
            "New Zealand European",
            "British nfd",
            "Celtic nfd",
            "Channel Islander",
            "Cornish",
            "English",
            "Irish",
            "Manx",
            "Scottish",
            "Welsh",
            "British nec",
            "Dutch",
            "Greek",
            "Polish",
            "South Slav nfd",
            "Croatian",
            "Dalmatian",
            "Macedonian",
            "Serbian",
            "Slovenian",
            "Bosnian",
            "South Slav nec",
            "Italian",
            "German",
            "Australian",
            "Albanian",
            "Armenian",
            "Austrian",
            "Belgian",
            "Bulgarian",
            "Belorussian",
            "Cypriot nfd",
            "Czech",
            "Danish",
            "Estonian",
            "Finnish",
            "Flemish",
            "French",
            "Hungarian",
            "Icelandic",
            "Latvian",
            "Lithuanian",
            "Maltese",
            "Norwegian",
            "Portuguese",
            "Romanian",
            "Gypsy",
            "Russian",
            "Slavic",
            "Slovak",
            "Spanish",
            "Swedish",
            "Swiss",
            "Ukrainian",
            "American",
            "Canadian",
            "New Caledonian",
            "South African European",
            "Afrikaner",
            "Zimbabwean European",
            "European nec"],
        "Maori":[
            "Maori"],
        "Pacific Peoples": [
            "Pacific Peoples nfd",
            "Samoan",
            "Cook Islands Maori",
            "Tongan",
            "Niuean",
            "Tokelauan",
            "Fijian",
            "Indigenous Australian",
            "Hawaiian",
            "Kiribati",
            "Nauruan",
            "Papua New Guinean",
            "Pitcairn Islander",
            "Rotuman",
            "Tahitian",
            "Solomon Islander",
            "Tuvaluan",
            "Ni Vanuatu",
            "Pacific Peoples nec"],
        "Asian": [
            "Asian nfd",
            "Southeast Asian nfd",
            "Filipino",
            "Cambodian",
            "Vietnamese",
            "Burmese",
            "Indonesian",
            "Lao",
            "Malay",
            "Thai",
            "Karen",
            "Chin",
            "Southeast Asian nec",
            "Chinese nfd",
            "Hong Kong Chinese",
            "Cambodian Chinese",
            "Malaysian Chinese",
            "Singaporean Chinese",
            "Vietnamese Chinese",
            "Taiwanese",
            "Chinese nec",
            "Indian nfd",
            "Bengali",
            "Fijian Indian",
            "Indian Tamil",
            "Punjabi",
            "Sikh",
            "Anglo Indian",
            "Malaysian Indian",
            "South African Indian",
            "Indian nec",
            "Sri Lankan nfd",
            "Sinhalese",
            "Sri Lankan Tamil",
            "Sri Lankan nec",
            "Japanese",
            "Korean",
            "Afghani",
            "Bangladeshi",
            "Nepalese",
            "Pakistani",
            "Tibetan",
            "Eurasian",
            "Bhutanese",
            "Maldivian",
            "Mongolian",
            "Asian nec"],
        "Middle Eastern/Latin American/African": [
            "Middle Eastern nfd",
            "Algerian",
            "Arab",
            "Assyrian",
            "Egyptian",
            "Iranian/Persian",
            "Iraqi",
            "Israeli/Jewish",
            "Jordanian",
            "Kurd",
            "Lebanese",
            "Moroccan",
            "Palestinian",
            "Syrian",
            "Turkish",
            "Middle Eastern nec",
            "Latin American nfd",
            "Argentinian",
            "Bolivian",
            "Brazilian",
            "Chilean",
            "Colombian",
            "Ecuadorian",
            "Mexican",
            "Peruvian",
            "Puerto Rican",
            "Uruguayan",
            "Venezuelan",
            "Latin American nec",
            "African nfd",
            "Jamaican",
            "Kenyan",
            "Nigerian",
            "African American",
            "Caribbean",
            "Somali",
            "Eritrean",
            "Ethiopian",
            "Ghanaian",
            "Burundian",
            "Congolese",
            "Sudanese",
            "Zambian",
            "Other Zimbabwean",
            "African nec"],
        "Other Ethnicity": [
            "Indigenous American",
            "Mauritian",
            "Seychellois",
            "Other South African",
            "New Zealander",
            "Other Ethnicity nec"],
        "Total people stated": [],
        "Not Elsewhere Included": []}
    }

def all_entries(d):
    el = []
    for k,v in d.items():
        el.append(k)
        if issubclass(type(v), dict):
            el.extend(all_entries(v))
        elif issubclass(type(v), list):
            el.extend(v)
        else: raise ValueError("entry is not a hierarchical list")
    return el

all_ethnic_groups = all_entries(ethnic_group_hierarchy)

unspecified_groups = ["Other Ethnicity nec", "Total people stated", "Not Elsewhere Included"]
assert all(x in all_ethnic_groups for x in unspecified_groups)

total_people_name = "Total people - ethnic group"
total_people_dict = ethnic_group_hierarchy[total_people_name]
total_people_sublevels = list(total_people_dict.keys())

race_counted_groups = set(chain(*total_people_dict.values())) - set(unspecified_groups)
